spring:

  application:
    name: WebsocketChat

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  session:
    redis:
      repository-type: default
      namespace: spring:session
      flush-mode: on_save

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6380}
      password: ${REDIS_PASSWORD:def_pwd}


  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: ${PUBLIC_KEY_LOCATION:classpath:certs/public.pem}

rsa:
  private-key: ${PRIVATE_KEY_LOCATION:classpath:certs/private.pem}
  public-key: ${PUBLIC_KEY_LOCATION:classpath:certs/public.pem}
