name: SonarQube Analysis

on:
  push:
    branches:
      - master
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  analysis:
    name: project analysis
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 23
        uses: actions/setup-java@v5
        with:
          java-version: '23'
          distribution: 'oracle'
          cache: maven
      #      - name: Cache SonarQube packages
      #        uses: actions/cache@v4
      #        with:
      #          path: ~/.sonar/cache
      #          key: ${{ runner.os }}-sonar
      #          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: mvn -B verify -DNVD_API_KEY=$NVD_API_KEY -Dsonar.token=$SONAR_TOKEN -Dsonar.organization=$SONAR_ORGANIZATION -Dspring.profiles.active=test
          
